"""Add likes table

Revision ID: 7fe435a3a018
Revises: 945a22290f0c
Create Date: 2026-01-23 15:08:44.200207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe435a3a018'
down_revision: Union[str, Sequence[str], None] = '945a22290f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('likes_user_id_fkey'), 'likes', type_='foreignkey')
    op.drop_constraint(op.f('likes_meme_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'memes', ['meme_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_meme_id_fkey'), 'likes', 'memes', ['meme_id'], ['id'])
    op.create_foreign_key(op.f('likes_user_id_fkey'), 'likes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
