"""add has_audio to memes

Revision ID: 94914339ec89
Revises: c620e9230963
Create Date: 2026-01-26 09:29:33.885289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94914339ec89'
down_revision: Union[str, Sequence[str], None] = 'c620e9230963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('has_audio', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memes', 'has_audio')
    # ### end Alembic commands ###
