"""add shares count

Revision ID: fd09dcfe1afb
Revises: ce92fd683f40
Create Date: 2026-02-04 11:46:31.703206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd09dcfe1afb'
down_revision: Union[str, Sequence[str], None] = 'ce92fd683f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('shares_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memes', 'shares_count')
    # ### end Alembic commands ###
